from django.urls import path

from tripmate import admin_dashboard_views as views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("login/", views.admin_login, name="admin_login"),
    path("logout/", views.admin_logout, name="logout"),
    path("forgot-password/", views.admin_forgot_password, name="admin_forgot_password"),
    path("reset-password/", views.admin_reset_password, name="admin_reset_password"),
    path("register/", views.admin_register, name="admin_register"),
    path("profile/", views.profile, name="profile"),
    path("settings/", views.admin_settings, name="settings"),
    path("lock-screen/", views.lock_screen, name="lock_screen"),
    path("toggle-theme/", views.toggle_theme, name="toggle_theme"),
    path("users/", views.admin_users, name="admin_users"),
    path("users/<int:user_id>/", views.admin_user_details, name="admin_user_details"),
    path("users/<int:user_id>/toggle-active/", views.admin_toggle_user_active, name="admin_toggle_user_active"),
    path("users/<int:user_id>/force-password-reset/", views.admin_force_password_reset, name="admin_force_password_reset"),
    path("users/<int:user_id>/delete/", views.admin_delete_user, name="admin_delete_user"),
    path("transporters/", views.admin_transporters, name="admin_transporters"),
    path("partner-features/", views.admin_partner_features, name="admin_partner_features"),
    path("notifications/", views.admin_notifications, name="admin_notifications"),
    path("app-releases/", views.admin_app_releases, name="admin_app_releases"),
    path("vehicles/", views.admin_vehicles, name="admin_vehicles"),
    path("drivers/", views.admin_drivers, name="admin_drivers"),
    path("attendance/", views.admin_attendance, name="admin_attendance"),
    path("trips/", views.admin_trips, name="admin_trips"),
    path("trips/<int:trip_id>/update-session/", views.admin_update_trip_session, name="admin_update_trip_session"),
    path("trips/<int:trip_id>/delete/", views.admin_delete_trip, name="admin_delete_trip"),
    path("fuel-records/", views.admin_fuel_records, name="admin_fuel_records"),
    path("fuel-records/<int:record_id>/delete/", views.admin_delete_fuel_record, name="admin_delete_fuel_record"),
    path("fuel-records/<int:record_id>/photo/", views.admin_fuel_record_photo, name="admin_fuel_record_photo"),
    path("diesel-tripsheet/", views.admin_diesel_tripsheet, name="admin_diesel_tripsheet"),
    path("diesel-sites/", views.admin_diesel_sites, name="admin_diesel_sites"),
    path("diesel-site-lookup/", views.admin_diesel_site_lookup, name="admin_diesel_site_lookup"),
    path("diesel-manual-entry/", views.admin_diesel_manual_entry, name="admin_diesel_manual_entry"),
    path("manual-vehicle-trips/", views.admin_manual_vehicle_trip_entry, name="admin_manual_vehicle_trip_entry"),
    path("reports/monthly/", views.admin_monthly_reports, name="admin_monthly_reports"),
    path("reports/monthly/diesel-pdf/", views.admin_monthly_diesel_pdf, name="admin_monthly_diesel_pdf"),
    path("audit-logs/", views.admin_audit_logs, name="admin_audit_logs"),
    path("export/<str:report_type>/", views.admin_export_report, name="admin_export_report"),
]
