from django.urls import path

from tripmate import admin_dashboard_views as views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("manifest.webmanifest", views.admin_pwa_manifest, name="admin_pwa_manifest"),
    path("service-worker.js", views.admin_service_worker, name="admin_service_worker"),
    path("offline/", views.admin_offline, name="admin_offline"),
    path("login/", views.admin_login, name="admin_login"),
    path("logout/", views.admin_logout, name="logout"),
    path("forgot-password/", views.admin_forgot_password, name="admin_forgot_password"),
    path("reset-password/", views.admin_reset_password, name="admin_reset_password"),
    path("register/", views.admin_register, name="admin_register"),
    path("profile/", views.profile, name="profile"),
    path("settings/", views.admin_settings, name="settings"),
    path("lock-screen/", views.lock_screen, name="lock_screen"),
    path("toggle-theme/", views.toggle_theme, name="toggle_theme"),
    path("users/", views.admin_users, name="admin_users"),
    path("users/<int:user_id>/", views.admin_user_details, name="admin_user_details"),
    path("users/<int:user_id>/toggle-active/", views.admin_toggle_user_active, name="admin_toggle_user_active"),
    path("users/<int:user_id>/force-password-reset/", views.admin_force_password_reset, name="admin_force_password_reset"),
    path("users/<int:user_id>/force-logout/", views.admin_force_user_logout, name="admin_force_user_logout"),
    path("users/<int:user_id>/delete/", views.admin_delete_user, name="admin_delete_user"),
    path(
        "account-deletion-requests/",
        views.admin_account_deletion_requests,
        name="admin_account_deletion_requests",
    ),
    path(
        "account-deletion-requests/<int:request_id>/process/",
        views.admin_process_account_deletion_request,
        name="admin_process_account_deletion_request",
    ),
    path(
        "account-deletion-requests/<int:request_id>/delete/",
        views.admin_delete_account_deletion_request,
        name="admin_delete_account_deletion_request",
    ),
    path("transporters/", views.admin_transporters, name="admin_transporters"),
    path("partner-features/", views.admin_partner_features, name="admin_partner_features"),
    path(
        "partner-features/<int:partner_id>/",
        views.admin_partner_feature_detail,
        name="admin_partner_feature_detail",
    ),
    path("notifications/", views.admin_notifications, name="admin_notifications"),
    path("app-releases/", views.admin_app_releases, name="admin_app_releases"),
    path("app-version-usage/", views.admin_app_version_usage, name="admin_app_version_usage"),
    path("auth-monitor/", views.admin_auth_monitor, name="admin_auth_monitor"),
    path("vehicles/", views.admin_vehicles, name="admin_vehicles"),
    path("drivers/", views.admin_drivers, name="admin_drivers"),
    path("attendance/", views.admin_attendance, name="admin_attendance"),
    path("run-exceptions/", views.admin_run_exceptions, name="admin_run_exceptions"),
    path("driver-locations/", views.admin_driver_locations, name="admin_driver_locations"),
    path("driver-locations/data/", views.admin_driver_locations_data, name="admin_driver_locations_data"),
    path("trips/", views.admin_trips, name="admin_trips"),
    path("trips/<int:trip_id>/update-session/", views.admin_update_trip_session, name="admin_update_trip_session"),
    path("trips/<int:trip_id>/delete/", views.admin_delete_trip, name="admin_delete_trip"),
    path("fuel-records/", views.admin_fuel_records, name="admin_fuel_records"),
    path("fuel-records/<int:record_id>/delete/", views.admin_delete_fuel_record, name="admin_delete_fuel_record"),
    path("fuel-records/<int:record_id>/photo/", views.admin_fuel_record_photo, name="admin_fuel_record_photo"),
    path("diesel-tripsheet/", views.admin_diesel_tripsheet, name="admin_diesel_tripsheet"),
    path("diesel-sites/", views.admin_diesel_sites, name="admin_diesel_sites"),
    path(
        "diesel-daily-route-plan/vehicles/",
        views.admin_diesel_daily_plan_vehicle_options,
        name="admin_diesel_daily_plan_vehicle_options",
    ),
    path(
        "diesel-daily-route-plan/drivers/",
        views.admin_diesel_daily_plan_driver_options,
        name="admin_diesel_daily_plan_driver_options",
    ),
    path(
        "diesel-daily-route-plan/sites/",
        views.admin_diesel_daily_plan_site_search,
        name="admin_diesel_daily_plan_site_search",
    ),
    path("diesel-daily-route-plan/", views.admin_diesel_daily_route_plan, name="admin_diesel_daily_route_plan"),
    path("diesel-route-planner/", views.admin_diesel_route_planner, name="admin_diesel_route_planner"),
    path("diesel-site-lookup/", views.admin_diesel_site_lookup, name="admin_diesel_site_lookup"),
    path("diesel-manual-entry/", views.admin_diesel_manual_entry, name="admin_diesel_manual_entry"),
    path("manual-vehicle-trips/", views.admin_manual_vehicle_trip_entry, name="admin_manual_vehicle_trip_entry"),
    path("reports/monthly/", views.admin_monthly_reports, name="admin_monthly_reports"),
    path("reports/monthly/diesel-pdf/", views.admin_monthly_diesel_pdf, name="admin_monthly_diesel_pdf"),
    path("server-health/", views.admin_server_health, name="admin_server_health"),
    path("server-health/backup-metadata/", views.admin_backup_metadata_download, name="admin_backup_metadata_download"),
    path(
        "server-health/backups/<str:backup_type>/<str:file_name>/download/",
        views.admin_backup_file_download,
        name="admin_backup_file_download",
    ),
    path(
        "server-health/backups/<str:backup_type>/<str:file_name>/delete/",
        views.admin_backup_file_delete,
        name="admin_backup_file_delete",
    ),
    path("audit-logs/", views.admin_audit_logs, name="admin_audit_logs"),
    path("export/<str:report_type>/", views.admin_export_report, name="admin_export_report"),
]
