# Generated by Django 6.0.2 on 2026-03-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('TRANSPORTER_SIGNUP', 'Transporter Signup'), ('DRIVER_SIGNUP', 'Driver Signup')], max_length=40),
        ),
    ]
