# Generated by Django 6.0.2 on 2026-03-05 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='diesel_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FeatureToggleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(default='diesel_module', max_length=80)),
                ('action', models.CharField(choices=[('ENABLED', 'Enabled'), ('DISABLED', 'Disabled')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='feature_toggle_logs', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_toggle_logs', to='users.transporter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
