# Generated by Django 6.0.2 on 2026-03-06 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0004_driver_default_service"),
        ("trips", "0003_trip_parent_trip_and_more"),
        ("users", "0006_transporter_diesel_tracking_enabled_featuretogglelog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransporterNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("TRIP_STARTED", "Trip Started"),
                            ("TRIP_CLOSED", "Trip Closed"),
                            ("START_DAY_REMINDER", "Start Day Reminder"),
                            ("OPEN_TRIP_ALERT", "Open Trip Alert"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("message", models.TextField()),
                ("event_key", models.CharField(blank=True, max_length=140, null=True, unique=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="drivers.driver",
                    ),
                ),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="users.transporter",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
