# Generated by Django 6.0.2 on 2026-03-06 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_trip_parent_trip_and_more"),
        ("drivers", "0004_driver_default_service"),
        ("users", "0008_adminbroadcastnotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ATTENDANCE_MARK_UPDATED", "Attendance Mark Updated"),
                            ("START_DAY_MISSED", "Start Day Missed"),
                            ("TRIP_OVERDUE", "Trip Overdue"),
                            ("FUEL_ANOMALY", "Fuel Anomaly"),
                            ("DIESEL_MODULE_TOGGLED", "Diesel Module Toggled"),
                            ("MONTH_END_REMINDER", "Month End Reminder"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("message", models.TextField()),
                ("event_key", models.CharField(blank=True, max_length=140, null=True, unique=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_notifications",
                        to="drivers.driver",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_notifications",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
