# Generated by Django 6.0.2 on 2026-03-05 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_drivernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivernotification',
            name='notification_type',
            field=models.CharField(choices=[('ATTENDANCE_MARK_UPDATED', 'Attendance Mark Updated'), ('START_DAY_MISSED', 'Start Day Missed'), ('TRIP_OVERDUE', 'Trip Overdue'), ('FUEL_ANOMALY', 'Fuel Anomaly'), ('DIESEL_MODULE_TOGGLED', 'Diesel Module Toggled'), ('MONTH_END_REMINDER', 'Month End Reminder'), ('WELCOME_ALLOCATED', 'Welcome Allocated'), ('SYSTEM', 'System')], max_length=40),
        ),
        migrations.AlterField(
            model_name='transporternotification',
            name='notification_type',
            field=models.CharField(choices=[('TRIP_STARTED', 'Trip Started'), ('TRIP_CLOSED', 'Trip Closed'), ('START_DAY_REMINDER', 'Start Day Reminder'), ('OPEN_TRIP_ALERT', 'Open Trip Alert'), ('TRIP_OVERDUE', 'Trip Overdue'), ('FUEL_ANOMALY', 'Fuel Anomaly'), ('MONTH_END_REMINDER', 'Month End Reminder'), ('DIESEL_MODULE_TOGGLED', 'Diesel Module Toggled'), ('SYSTEM', 'System')], max_length=40),
        ),
        migrations.CreateModel(
            name='UserDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ANDROID', 'Android'), ('IOS', 'iOS'), ('WEB', 'Web')], default='ANDROID', max_length=20)),
                ('app_variant', models.CharField(choices=[('DRIVER', 'Driver'), ('TRANSPORTER', 'Transporter'), ('GENERIC', 'Generic')], default='GENERIC', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
