# Generated by Django 6.0.2 on 2026-03-07 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_drivernotification_notification_type_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_variant', models.CharField(choices=[('DRIVER', 'Driver'), ('TRANSPORTER', 'Transporter')], max_length=20)),
                ('version_name', models.CharField(max_length=32)),
                ('build_number', models.PositiveIntegerField()),
                ('apk_file', models.FileField(upload_to='app_updates/%Y/%m/')),
                ('force_update', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_app_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['app_variant', '-build_number', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('app_variant', 'version_name', 'build_number'), name='unique_app_release_variant_version_build')],
            },
        ),
    ]
