# Generated by Django 6.0.2 on 2026-03-07 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_transporter_salary_auto_email_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('app_variant', models.CharField(choices=[('DRIVER', 'Driver'), ('TRANSPORTER', 'Transporter'), ('ADMIN', 'Admin'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGOUT_NORMAL', 'Normal Logout'), ('TOKEN_EXPIRED', 'Token Expired'), ('TOKEN_INVALID', 'Token Invalid')], max_length=32)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('path', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('token_jti', models.CharField(blank=True, max_length=64)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_session_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='users_auths_event_t_d388b6_idx'), models.Index(fields=['app_variant', 'created_at'], name='users_auths_app_var_1a95e7_idx'), models.Index(fields=['user', 'created_at'], name='users_auths_user_id_71ccb4_idx')],
            },
        ),
    ]
