# Generated by Django 6.0.2 on 2026-03-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_authsessionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdevicetoken',
            name='app_build_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdevicetoken',
            name='app_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='authsessionevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGOUT_NORMAL', 'Normal Logout'), ('LOGOUT_FORCED', 'Forced Logout'), ('TOKEN_EXPIRED', 'Token Expired'), ('TOKEN_INVALID', 'Token Invalid')], max_length=32),
        ),
    ]
