# Generated by Django 6.0.2 on 2026-03-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_transporter_location_tracking_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='gstin',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='transporter',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='transporters/logos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='transporter',
            name='pan',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='transporter',
            name='website',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
