# Generated by Django 6.0.2 on 2026-03-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_transporter_gstin_transporter_logo_transporter_pan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='diesel_readings_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
