# Generated by Django 6.0.2 on 2026-03-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_accountdeletionrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('TRANSPORTER_SIGNUP', 'Transporter Signup'), ('DRIVER_SIGNUP', 'Driver Signup'), ('DRIVER_ALLOCATION', 'Driver Allocation'), ('PASSWORD_RESET', 'Password Reset'), ('PROFILE_EMAIL_CHANGE', 'Profile Email Change')], max_length=40),
        ),
    ]
