# Generated by Django 6.0.2 on 2026-03-30 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_nonce',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('TRANSPORTER_SIGNUP', 'Transporter Signup'), ('DRIVER_SIGNUP', 'Driver Signup'), ('DRIVER_LOGIN', 'Driver Login'), ('DRIVER_ALLOCATION', 'Driver Allocation'), ('PASSWORD_RESET', 'Password Reset'), ('PROFILE_EMAIL_CHANGE', 'Profile Email Change'), ('ACCOUNT_DELETION', 'Account Deletion')], max_length=40),
        ),
    ]
