# Generated by Django 6.0.2 on 2026-03-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_session_nonce_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('TRANSPORTER_SIGNUP', 'Transporter Signup'), ('DRIVER_SIGNUP', 'Driver Signup'), ('TRANSPORTER_LOGIN', 'Transporter Login'), ('DRIVER_LOGIN', 'Driver Login'), ('DRIVER_ALLOCATION', 'Driver Allocation'), ('PASSWORD_RESET', 'Password Reset'), ('PROFILE_EMAIL_CHANGE', 'Profile Email Change'), ('ACCOUNT_DELETION', 'Account Deletion')], max_length=40),
        ),
    ]
