server {
    server_name 13-60-219-105.sslip.io 13.60.219.105;

    client_max_body_size 30M;

    location /static/ {
        alias /home/ubuntu/TripMate-main/staticfiles/;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location /media/ {
        alias /home/ubuntu/TripMate-main/media/;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
    }

    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/13-60-219-105.sslip.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/13-60-219-105.sslip.io/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = 13-60-219-105.sslip.io) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    listen [::]:80;
    server_name 13-60-219-105.sslip.io;
    return 301 https://$host$request_uri;
}

server {
    listen 80;
    listen [::]:80;
    server_name 13.60.219.105;

    client_max_body_size 30M;

    location /static/ {
        alias /home/ubuntu/TripMate-main/staticfiles/;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location /media/ {
        alias /home/ubuntu/TripMate-main/media/;
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
    }
}
