# Generated by Django 6.0.2 on 2026-03-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0010_alter_drivernotification_notification_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndusTowerSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("indus_site_id", models.CharField(max_length=64)),
                ("site_name", models.CharField(max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indus_tower_sites",
                        to="users.transporter",
                    ),
                ),
            ],
            options={
                "ordering": ["site_name", "indus_site_id"],
                "indexes": [
                    models.Index(
                        fields=["partner", "indus_site_id"],
                        name="diesel_indu_partner_8c5f53_idx",
                    ),
                    models.Index(
                        fields=["partner", "site_name"],
                        name="diesel_indu_partner_e2f570_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("partner", "indus_site_id"),
                        name="unique_indus_site_id_per_partner",
                    )
                ],
            },
        ),
    ]
