# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diesel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industowersite",
            name="site_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
