# Generated by Django 6.0.2 on 2026-03-10 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diesel', '0002_alter_industowersite_site_name'),
        ('users', '0016_transporter_location_tracking_enabled'),
        ('vehicles', '0003_vehicle_tank_capacity_liters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DieselDailyRoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_diesel_daily_route_plans', to=settings.AUTH_USER_MODEL)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diesel_daily_route_plans', to='users.transporter')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diesel_daily_route_plans', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-plan_date', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DieselDailyRoutePlanStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('indus_site_id', models.CharField(blank=True, default='', max_length=64)),
                ('site_name', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('planned_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='diesel.dieseldailyrouteplan')),
                ('tower_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_route_stops', to='diesel.industowersite')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DieselRouteStartPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Depot', max_length=120)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diesel_route_start_point', to='users.transporter')),
            ],
            options={
                'ordering': ['transporter_id'],
            },
        ),
        migrations.AddIndex(
            model_name='dieseldailyrouteplan',
            index=models.Index(fields=['vehicle', 'plan_date'], name='diesel_dies_vehicle_844290_idx'),
        ),
        migrations.AddIndex(
            model_name='dieseldailyrouteplan',
            index=models.Index(fields=['transporter', 'plan_date'], name='diesel_dies_transpo_61990b_idx'),
        ),
        migrations.AddConstraint(
            model_name='dieseldailyrouteplan',
            constraint=models.UniqueConstraint(fields=('vehicle', 'plan_date'), name='unique_diesel_daily_plan_per_vehicle_per_day'),
        ),
        migrations.AddIndex(
            model_name='dieseldailyrouteplanstop',
            index=models.Index(fields=['plan', 'sequence'], name='diesel_dies_plan_id_3a58a5_idx'),
        ),
        migrations.AddIndex(
            model_name='dieseldailyrouteplanstop',
            index=models.Index(fields=['plan', 'tower_site'], name='diesel_dies_plan_id_c615f0_idx'),
        ),
    ]
