# Generated by Django 6.0.2 on 2026-03-05 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_service_name_attendance_service_purpose_and_more'),
        ('drivers', '0003_alter_driver_transporter'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='default_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_drivers', to='attendance.transportservice'),
        ),
    ]
