# Generated by Codex on 2026-03-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0016_transporter_location_tracking_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransporterBillRecipient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(help_text="Multi-line address")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bill_recipients",
                        to="users.transporter",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TransporterBankDetails",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("branch", models.CharField(blank=True, max_length=120)),
                ("account_no", models.CharField(blank=True, max_length=64)),
                ("ifsc_code", models.CharField(blank=True, max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transporter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_details",
                        to="users.transporter",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="transporterbillrecipient",
            index=models.Index(fields=["transporter", "name"], name="reports_tra_transpo_6ef9b9_idx"),
        ),
    ]
