# Generated by Django 6.0.2 on 2026-03-18 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_transporter_billing_models'),
        ('users', '0016_transporter_location_tracking_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterBillHeaderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gstin', models.CharField(blank=True, max_length=32)),
                ('pan', models.CharField(blank=True, max_length=32)),
                ('website', models.CharField(blank=True, max_length=120)),
                ('biller_name', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transporter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill_header_details', to='users.transporter')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TransporterVehicleBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, max_length=40)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vehicle_number', models.CharField(max_length=40)),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('extra_km', models.PositiveIntegerField(default=0)),
                ('extra_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('to_name', models.CharField(max_length=255)),
                ('to_address', models.TextField()),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('account_no', models.CharField(blank=True, max_length=64)),
                ('ifsc_code', models.CharField(blank=True, max_length=32)),
                ('from_company_name', models.CharField(blank=True, max_length=255)),
                ('from_contact_name', models.CharField(blank=True, max_length=255)),
                ('from_phone', models.CharField(blank=True, max_length=32)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_gstin', models.CharField(blank=True, max_length=32)),
                ('from_pan', models.CharField(blank=True, max_length=32)),
                ('from_website', models.CharField(blank=True, max_length=120)),
                ('biller_name', models.CharField(blank=True, max_length=255)),
                ('pdf_file', models.FileField(blank=True, upload_to='vehicle_bills/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_bills', to='reports.transporterbillrecipient')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_bills', to='users.transporter')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transporter', 'created_at'], name='reports_tra_transpo_8012f3_idx'), models.Index(fields=['transporter', 'bill_no'], name='reports_tra_transpo_94a5d1_idx')],
                'constraints': [models.UniqueConstraint(fields=('transporter', 'bill_no'), name='unique_transporter_vehicle_bill_no')],
            },
        ),
    ]
