# Generated by Django 6.0.2 on 2026-03-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrecord',
            name='odometer_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
