# Generated by Django 6.0.2 on 2026-03-05 16:29

import django.db.models.deletion
import django.utils.timezone
import fuel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_fuelrecord_odometer_km'),
        ('users', '0006_transporter_diesel_tracking_enabled_featuretogglelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrecord',
            name='end_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='entry_type',
            field=models.CharField(choices=[('VEHICLE_FILLING', 'Vehicle Fuel Filling'), ('TOWER_DIESEL', 'Tower Diesel Filling')], db_index=True, default='VEHICLE_FILLING', max_length=24),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='fill_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='fuel_filled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='indus_site_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='logbook_photo',
            field=models.ImageField(blank=True, null=True, upload_to=fuel.models.diesel_logbook_upload_to),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='ocr_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='ocr_raw_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diesel_fill_logs', to='users.transporter'),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='purpose',
            field=models.CharField(blank=True, default='Diesel Filling', max_length=255),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='run_km',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='site_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='start_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to='fuel/bill/'),
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='meter_image',
            field=models.ImageField(blank=True, null=True, upload_to='fuel/meter/'),
        ),
    ]
