# Generated by Django 6.0.2 on 2026-03-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel", "0004_fuelrecord_end_km_fuelrecord_entry_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelrecord",
            name="tower_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="fuelrecord",
            name="tower_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
