# Generated by Django 6.0.2 on 2026-03-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diesel", "0001_initial"),
        ("fuel", "0005_fuelrecord_tower_latitude_fuelrecord_tower_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelrecord",
            name="tower_site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fill_logs",
                to="diesel.industowersite",
            ),
        ),
    ]
