# Generated by Django 6.0.2 on 2026-03-06

from django.db import migrations


def backfill_tower_sites(apps, schema_editor):
    FuelRecord = apps.get_model("fuel", "FuelRecord")
    Driver = apps.get_model("drivers", "Driver")
    IndusTowerSite = apps.get_model("diesel", "IndusTowerSite")
    db_alias = schema_editor.connection.alias

    driver_partner_map = dict(
        Driver.objects.using(db_alias).values_list("id", "transporter_id")
    )
    site_cache = {}

    queryset = FuelRecord.objects.using(db_alias).filter(
        entry_type="TOWER_DIESEL",
    )
    for record in queryset.iterator(chunk_size=200):
        if record.tower_site_id:
            continue

        site_id = (record.indus_site_id or "").strip()
        if not site_id:
            continue

        partner_id = record.partner_id or driver_partner_map.get(record.driver_id)
        if not partner_id:
            continue

        site_name = (record.site_name or "").strip() or site_id
        cache_key = (partner_id, site_id.upper())
        tower_site = site_cache.get(cache_key)
        if tower_site is None:
            tower_site = (
                IndusTowerSite.objects.using(db_alias)
                .filter(
                    partner_id=partner_id,
                    indus_site_id__iexact=site_id,
                )
                .order_by("id")
                .first()
            )
            if tower_site is None:
                tower_site = IndusTowerSite.objects.using(db_alias).create(
                    partner_id=partner_id,
                    indus_site_id=site_id,
                    site_name=site_name,
                    latitude=record.tower_latitude,
                    longitude=record.tower_longitude,
                )
            else:
                fields_to_update = []
                if site_name and tower_site.site_name != site_name:
                    tower_site.site_name = site_name
                    fields_to_update.append("site_name")
                if record.tower_latitude is not None and tower_site.latitude is None:
                    tower_site.latitude = record.tower_latitude
                    fields_to_update.append("latitude")
                if record.tower_longitude is not None and tower_site.longitude is None:
                    tower_site.longitude = record.tower_longitude
                    fields_to_update.append("longitude")
                if fields_to_update:
                    fields_to_update.append("updated_at")
                    tower_site.save(update_fields=fields_to_update)
            site_cache[cache_key] = tower_site

        record.tower_site_id = tower_site.id
        record.save(update_fields=["tower_site"])


def noop_reverse(_apps, _schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ("diesel", "0001_initial"),
        ("fuel", "0006_fuelrecord_tower_site"),
    ]

    operations = [
        migrations.RunPython(backfill_tower_sites, noop_reverse),
    ]
