# Generated by Django 6.0.2 on 2026-03-06 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_attendance_unique_driver_attendance_per_day'),
        ('fuel', '0007_backfill_tower_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrecord',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_records', to='attendance.attendance'),
        ),
    ]
