# Generated by Django 6.0.2 on 2026-03-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0008_alter_fuelrecord_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrecord',
            name='dg_hmr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='opening_stock',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='piu_reading',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
