# Generated by Django 6.0.2 on 2026-03-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('DIESEL_SERVICE', 'Diesel Service')], default='GENERAL', max_length=30),
        ),
    ]
