from django.urls import path

from users.views import (
    AdminPartnerDieselToggleView,
    AdminForceLogoutView,
    AppUpdateView,
    ChangePasswordView,
    DriverNotificationListView,
    DriverLoginOtpRequestView,
    DriverLoginOtpVerifyView,
    DriverNotificationMarkReadView,
    DriverOtpRequestView,
    DriverRegisterView,
    LoginView,
    LogoutView,
    PasswordResetConfirmView,
    PasswordResetOtpRequestView,
    ProfileView,
    ProfileAccountDeletionView,
    ProfileAccountDeletionOtpRequestView,
    ProfileEmailChangeOtpRequestView,
    PushTokenRegisterView,
    PushTokenUnregisterView,
    SessionRefreshView,
    TransporterLoginOtpRequestView,
    TransporterLoginOtpVerifyView,
    TransporterNotificationListView,
    TransporterNotificationMarkReadView,
    TransporterOtpRequestView,
    TransporterPublicListView,
    TransporterRegisterView,
)

urlpatterns = [
    path("login", LoginView.as_view(), name="login"),
    path("token/refresh", SessionRefreshView.as_view(), name="token-refresh"),
    path("logout", LogoutView.as_view(), name="logout-api"),
    path("profile", ProfileView.as_view(), name="profile"),
    path(
        "profile/request-email-otp",
        ProfileEmailChangeOtpRequestView.as_view(),
        name="profile-request-email-otp",
    ),
    path(
        "profile/request-account-deletion-otp",
        ProfileAccountDeletionOtpRequestView.as_view(),
        name="profile-request-account-deletion-otp",
    ),
    path(
        "profile/account-deletion",
        ProfileAccountDeletionView.as_view(),
        name="profile-account-deletion",
    ),
    path("profile/change-password", ChangePasswordView.as_view(), name="profile-change-password"),
    path(
        "notifications",
        TransporterNotificationListView.as_view(),
        name="transporter-notifications",
    ),
    path(
        "notifications/mark-read",
        TransporterNotificationMarkReadView.as_view(),
        name="transporter-notifications-mark-read",
    ),
    path(
        "driver/notifications",
        DriverNotificationListView.as_view(),
        name="driver-notifications",
    ),
    path(
        "driver/notifications/mark-read",
        DriverNotificationMarkReadView.as_view(),
        name="driver-notifications-mark-read",
    ),
    path(
        "admin/partner/enable_diesel_module",
        AdminPartnerDieselToggleView.as_view(),
        name="admin-partner-enable-diesel-module-underscore",
    ),
    path(
        "admin/partner/enable-diesel-module",
        AdminPartnerDieselToggleView.as_view(),
        name="admin-partner-enable-diesel-module",
    ),
    path(
        "admin/users/<int:user_id>/force-logout",
        AdminForceLogoutView.as_view(),
        name="admin-user-force-logout-api",
    ),
    path("transporters/public", TransporterPublicListView.as_view(), name="transporter-public-list"),
    path("transporter/request-otp", TransporterOtpRequestView.as_view(), name="transporter-request-otp"),
    path(
        "transporter/login/request-otp",
        TransporterLoginOtpRequestView.as_view(),
        name="transporter-login-request-otp",
    ),
    path(
        "transporter/login/verify-otp",
        TransporterLoginOtpVerifyView.as_view(),
        name="transporter-login-verify-otp",
    ),
    path("transporter/register", TransporterRegisterView.as_view(), name="transporter-register"),
    path("driver/request-otp", DriverOtpRequestView.as_view(), name="driver-request-otp"),
    path(
        "driver/login/request-otp",
        DriverLoginOtpRequestView.as_view(),
        name="driver-login-request-otp",
    ),
    path(
        "driver/login/verify-otp",
        DriverLoginOtpVerifyView.as_view(),
        name="driver-login-verify-otp",
    ),
    path("driver/register", DriverRegisterView.as_view(), name="driver-register"),
    path("push/register-token", PushTokenRegisterView.as_view(), name="push-register-token"),
    path("push/unregister-token", PushTokenUnregisterView.as_view(), name="push-unregister-token"),
    path("app-update/<str:app_variant>", AppUpdateView.as_view(), name="app-update"),
    path(
        "password/request-otp",
        PasswordResetOtpRequestView.as_view(),
        name="password-reset-request-otp",
    ),
    path(
        "password/request-otp/",
        PasswordResetOtpRequestView.as_view(),
        name="password-reset-request-otp-slash",
    ),
    path(
        "password/reset",
        PasswordResetConfirmView.as_view(),
        name="password-reset-confirm",
    ),
    path(
        "password/reset/",
        PasswordResetConfirmView.as_view(),
        name="password-reset-confirm-slash",
    ),
    path(
        "forgot-password/request-otp",
        PasswordResetOtpRequestView.as_view(),
        name="forgot-password-request-otp",
    ),
    path(
        "forgot-password/request-otp/",
        PasswordResetOtpRequestView.as_view(),
        name="forgot-password-request-otp-slash",
    ),
    path(
        "forgot-password/reset",
        PasswordResetConfirmView.as_view(),
        name="forgot-password-reset",
    ),
    path(
        "forgot-password/reset/",
        PasswordResetConfirmView.as_view(),
        name="forgot-password-reset-slash",
    ),
]
