name: tripmate_mobile
description: Fleet management mobile apps with separate driver and transporter entrypoints.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  provider: ^6.1.2
  google_fonts: ^6.3.2
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  google_mlkit_text_recognition: ^0.14.0
  geolocator: ^13.0.1
  shared_preferences: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/branding/tripmate_icon.png
    - assets/branding/tripmate_wordmark.png
