# Generated by Django 6.0.2 on 2026-03-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_km', models.PositiveIntegerField()),
                ('end_km', models.PositiveIntegerField()),
                ('total_km', models.PositiveIntegerField(default=0)),
                ('purpose', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='attendance.attendance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
