# Generated by Django 6.0.2 on 2026-03-05 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-started_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='trip',
            name='end_odo_image',
            field=models.ImageField(blank=True, null=True, upload_to='trips/odo_end/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_day_trip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_odo_image',
            field=models.ImageField(blank=True, null=True, upload_to='trips/odo_start/'),
        ),
        migrations.AddField(
            model_name='trip',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='CLOSED', max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='end_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
