# Generated by Django 6.0.2 on 2026-03-05 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_end_latitude_attendance_end_longitude'),
        ('trips', '0002_alter_trip_options_trip_end_odo_image_trip_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='parent_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_trips', to='trips.trip'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(condition=models.Q(('is_day_trip', True), ('parent_trip__isnull', True)), fields=('attendance',), name='unique_master_trip_per_attendance'),
        ),
    ]
