# Generated by Django 6.0.2 on 2026-03-04 11:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('ON_DUTY', 'On Duty'), ('NO_TRIP', 'No Trip'), ('LEAVE', 'Leave')], default='ON_DUTY', max_length=20)),
                ('start_km', models.PositiveIntegerField()),
                ('end_km', models.PositiveIntegerField(blank=True, null=True)),
                ('odo_start_image', models.ImageField(upload_to='attendance/odo_start/')),
                ('odo_end_image', models.ImageField(blank=True, null=True, upload_to='attendance/odo_end/')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', '-started_at'],
            },
        ),
    ]
