# Generated by Django 6.0.2 on 2026-03-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='drivers.driver'),
        ),
    ]
