# Generated by Django 6.0.2 on 2026-03-05 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance_end_latitude_attendance_end_longitude'),
        ('users', '0004_alter_emailotp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='service_name',
            field=models.CharField(db_index=True, default='Unspecified Service', max_length=120),
        ),
        migrations.AddField(
            model_name='attendance',
            name='service_purpose',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='TransportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='users.transporter')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.transportservice'),
        ),
        migrations.AddConstraint(
            model_name='transportservice',
            constraint=models.UniqueConstraint(fields=('transporter', 'name'), name='unique_service_name_per_transporter'),
        ),
    ]
