# Generated by Django 6.0.2 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_attendance_service_name_attendance_service_purpose_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driverdailyattendancemark",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("LEAVE", "Leave"),
                ],
                max_length=10,
            ),
        ),
    ]
