# Generated by Django 6.0.2 on 2026-03-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_alter_driverdailyattendancemark_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_driver_attendance_per_day',
        ),
    ]
