# Generated by Django 6.0.2 on 2026-03-07 19:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_remove_driverdailyattendancemark_unique_driver_mark_per_day_and_more'),
        ('drivers', '0006_driver_joined_transporter_at'),
        ('users', '0015_user_session_revoked_at_and_more'),
        ('vehicles', '0003_vehicle_tank_capacity_liters'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLocationPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(choices=[('START', 'Start'), ('TRACK', 'Track'), ('END', 'End')], default='TRACK', max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('speed_kph', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_points', to='attendance.attendance')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_location_points', to='drivers.driver')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_location_points', to='users.transporter')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_location_points', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['recorded_at', 'id'],
                'indexes': [models.Index(fields=['attendance', 'recorded_at'], name='attendance__attenda_c013f6_idx'), models.Index(fields=['driver', 'recorded_at'], name='attendance__driver__78fb00_idx'), models.Index(fields=['transporter', 'recorded_at'], name='attendance__transpo_335a1f_idx')],
            },
        ),
    ]
